// Run Plaid Precheck
get http://localhost:3001/api/plaid/run_precheck
Content-Type: application/json

### Generate Link Token
post http://localhost:3001/api/plaid/generate_link_token
Content-Type: application/json